pipeline {
    agent none

    stages {
        stage('build and test nodej.js app') {
            agent {
                docker { image 'node:18-slim'}
            }
            steps {
                dir('nodejspython-app/anothernodejs-app') {
                    echo 'building nodejs app...'
                    sh 'node --version'
                    sh 'npm install'
                    sh 'npm start'
                    echo 'testing nodejs app'
                    sh 'npm test'
                }
            }
        }

        stage('building and testing python app') {
            agent {
                docker { image 'python:3.10-slim'}
            }
            steps {
                dir('nodejspython-app/python-app') {
                    echo 'building python app'
                    sh 'python --version'
                    sh 'pip install --no-cache-dir --disable-pip-version-check --ignore-installed --root-user-action=ignore -r requirements.txt'
                    sh 'pytest'
                }
            }
        }
    }
    post {

        always {
            echo 'pipeline finished'
        }

        success {
            echo 'this pipeline was successful'
        }

        failure {
            echo 'this pipeline failed'
        }
    }
}