pipeline {
    agent any

    stages {
        stage('build') {

            steps {
                dir('nodejs-app') {
                    echo 'building application...'
                    sh 'npm install'
                    sh 'npm start'
                }
            }
        }
        stage('test') {

            steps {
                dir('nodejs-app') {
                    echo 'testing application...'
                    sh 'npm test'
                }
            }
        }
        stage('deploy') {

            steps {
                dir('nodejs-app') {
                    echo 'deploying application...'
                    sh 'chmod +x deploy.sh'
                    sh './deploy.sh'
                }
            }
        }
    }
    post {
        always {
            echo 'pipeline finished (success or fail)'
        }

        success {
            echo 'the pipeline succeeded'
        }

        failure {
            echo 'the pipeline failed'
        }
    }
}